"""
Packages InfernoSaber output into a BeatSaver-compliant .zip.
Required zip structure:
  info.dat       ← map metadata (Beat Saber 2.0.0 schema)
  song.egg       ← audio (OGG renamed, or use ffmpeg to convert)
  cover.jpg      ← 512x512 cover art (can be generated via PIL)
  EasyStandard.dat
  NormalStandard.dat
  HardStandard.dat
  ExpertStandard.dat    ← generated by InfernoSaber
"""
import argparse, json, zipfile, shutil, subprocess
from pathlib import Path
from datetime import datetime

def build_info_dat(title, artist, audio_filename, difficulties):
    return {
        "_version": "2.0.0",
        "_songName": title,
        "_songSubName": "",
        "_songAuthorName": artist,
        "_levelAuthorName": "InfernoSaber-Bot",
        "_beatsPerMinute": 120,       # InfernoSaber writes actual BPM
        "_songFilename": audio_filename,
        "_coverImageFilename": "cover.jpg",
        "_environmentName": "DefaultEnvironment",
        "_difficultyBeatmapSets": [{
            "_beatmapCharacteristicName": "Standard",
            "_difficultyBeatmaps": [
                {"_difficulty": d, "_difficultyRank": r,
                 "_beatmapFilename": f"{d}Standard.dat",
                 "_noteJumpMovementSpeed": 10, "_noteJumpStartBeatOffset": 0}
                for d, r in difficulties
            ]
        }]
    }

parser = argparse.ArgumentParser()
parser.add_argument("--map-dir")
parser.add_argument("--title")
parser.add_argument("--artist")
parser.add_argument("--audio")
parser.add_argument("--out")
args = parser.parse_args()

map_dir = Path(args.map_dir)
out_zip = Path(args.out)
difficulties = [("Easy", 1), ("Normal", 3), ("Hard", 5), ("Expert", 7)]

# Convert audio to OGG (song.egg)
subprocess.run(["ffmpeg", "-y", "-i", args.audio, "-c:a", "libvorbis", "song.egg"], check=True)

info = build_info_dat(args.title, args.artist, "song.egg", difficulties)

with zipfile.ZipFile(out_zip, "w", zipfile.ZIP_DEFLATED) as zf:
    zf.writestr("info.dat", json.dumps(info, indent=2))
    zf.write("song.egg", "song.egg")
    # Generate minimal cover if none exists
    try:
        zf.write(map_dir / "cover.jpg", "cover.jpg")
    except FileNotFoundError:
        pass  # BeatSaver accepts maps without cover
    for diff, _ in difficulties:
        dat_path = map_dir / f"{diff}Standard.dat"
        if dat_path.exists():
            zf.write(dat_path, f"{diff}Standard.dat")
